#!/usr/bin/with-contenv sh

USER_ID=${DASPANEL_SYS_USERID:-1000}
echo "[DASPANEL] INFO: Starting with UID $USER_ID"
addgroup -g $USER_ID daspanel
adduser -s /bin/false -D -h /home/daspanel -u $USER_ID -G daspanel daspanel

# Installation UUID must be informed
if [ -z "$DASPANEL_SYS_UUID" ]; then
    echo "***"
    echo "ERROR: You must set the env variable DASPANEL_SYS_UUID to a valid UUID"
    echo "***"
    exit 1
fi

# API server 
if [ -z "$DASPANEL_SYS_APISERVER" ]; then
    export DASPANEL_SYS_APISERVER="http://daspanel-api:8080/1.0"
    printf $DASPANEL_SYS_APISERVER > /var/run/s6/container_environment/DASPANEL_SYS_APISERVER
fi

# API key 
if [ -z "$DASPANEL_SYS_APIKEY" ]; then
    export DASPANEL_SYS_APIKEY="$DASPANEL_SYS_UUID"
    printf $DASPANEL_SYS_APIKEY > /var/run/s6/container_environment/DASPANEL_SYS_APIKEY
fi

# If container need to wait API become online 
if [ -z "$DASPANEL_WAIT_FOR_API" ]; then
    export DASPANEL_WAIT_FOR_API="YES"
    printf $DASPANEL_WAIT_FOR_API > /var/run/s6/container_environment/DASPANEL_WAIT_FOR_API
fi

if [ ! -d "/opt/daspanel/data/$DASPANEL_SYS_UUID" ]; then
	mkdir -p "/opt/daspanel/data/$DASPANEL_SYS_UUID"
fi

if [ ! -d "/opt/daspanel/data/$DASPANEL_SYS_UUID/db" ]; then
	mkdir -p "/opt/daspanel/data/$DASPANEL_SYS_UUID/db"
fi

if [ ! -d "/opt/daspanel/log/$DASPANEL_SYS_UUID" ]; then
	mkdir -p "/opt/daspanel/log/$DASPANEL_SYS_UUID"
fi

# secure daspanel
chown -R $USER_ID:$USER_ID /opt/daspanel/data
chown -R $USER_ID:$USER_ID /opt/daspanel/log


